name: Publish to Maven

on:
  workflow_dispatch:

env:
  EC2_GENERATE_CONTENT_ID: ${{ secrets.EC2_GENERATE_CONTENT_ID }}
  GPR_USER: ${{ secrets.GPR_USER }}
  GPR_API_KEY: ${{ secrets.GPR_API_KEY }}

jobs:
  build:
    runs-on: android-hetzner-dedicated

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          clean: true

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build Android project
        run: |
          export ANDROID_HOME=$HOME/Android/Sdk
          export PATH="$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH"
          ./gradlew publishReleasePublicationToGitHubPackagesRepository
        if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/feature/')
